# Generated by Django 4.2.5 on 2023-10-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_perfil_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(default='default.jpg', upload_to='perfil_img'),
        ),
    ]
