# Generated by Django 4.2.4 on 2023-09-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.FloatField()),
                ('P', models.FloatField()),
                ('K', models.FloatField()),
                ('pH', models.FloatField()),
                ('EC', models.FloatField()),
                ('OC', models.FloatField()),
                ('S', models.FloatField()),
                ('Zn', models.FloatField()),
                ('Fe', models.FloatField()),
                ('Cu', models.FloatField()),
                ('Mn', models.FloatField()),
            ],
        ),
    ]
