# Generated by Django 4.2.5 on 2023-09-15 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_fertilex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.FloatField()),
                ('P', models.FloatField()),
                ('K', models.FloatField()),
                ('pH', models.FloatField()),
                ('EC', models.FloatField()),
                ('OC', models.FloatField()),
                ('S', models.FloatField()),
                ('Zn', models.FloatField()),
                ('Fe', models.FloatField()),
                ('Cu', models.FloatField()),
                ('Mn', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PrevisaoInput',
        ),
    ]
