# Generated by Django 4.2.5 on 2023-09-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_fertilex', '0002_previsao_delete_previsaoinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fertilex.previsao')),
            ],
        ),
    ]
