# Generated by Django 4.2.5 on 2023-09-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fertilex', '0004_remove_previsao_cu_remove_previsao_ec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsao',
            name='resultados',
            field=models.JSONField(default=list),
        ),
    ]
