# Generated by Django 4.2.5 on 2023-09-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fertilex', '0005_alter_previsao_resultados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
