# Generated by Django 4.2.5 on 2023-10-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fertilex', '0008_configuracaoprevisao_remove_previsao_num_linhas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoprevisao',
            name='standard_scaler',
            field=models.CharField(default='on', max_length=3),
        ),
    ]
