# Generated by Django 4.2.5 on 2023-10-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fertilex', '0009_alter_configuracaoprevisao_standard_scaler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoprevisao',
            name='standard_scaler',
            field=models.BooleanField(default=False),
        ),
    ]
