# Generated by Django 4.2.5 on 2023-10-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fertilex', '0010_alter_configuracaoprevisao_standard_scaler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracaoprevisao',
            old_name='id',
            new_name='id_config',
        ),
    ]
