# Generated by Django 4.2.5 on 2023-10-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fertilex', '0011_rename_id_configuracaoprevisao_id_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoprevisao',
            name='smote',
            field=models.BooleanField(default=False),
        ),
    ]
